// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Announcement: typeof import('./src/components/announcement/Announcement.vue')['default']
    Carousel: typeof import('./src/components/carousel/Carousel.vue')['default']
    ContentBody: typeof import('./src/components/contentBody/ContentBody.vue')['default']
    HelpBar: typeof import('./src/components/helpBar/HelpBar.vue')['default']
    LoadingBiggerHint: typeof import('./src/components/common/loading-hint/LoadingBiggerHint.vue')['default']
    LoadingCommonHint: typeof import('./src/components/common/loading-hint/LoadingCommonHint.vue')['default']
    PageFooter: typeof import('./src/components/pageFooter/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/pageHeader/PageHeader.vue')['default']
    RailWayLine: typeof import('./src/components/railwayLine/RailWayLine.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchTool: typeof import('./src/components/searchTools/SearchTool.vue')['default']
    ServiceBrand: typeof import('./src/components/serviceBrand/ServiceBrand.vue')['default']
    ServiceList: typeof import('./src/components/serviceList/ServiceList.vue')['default']
  }
}

export {}
