// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Announcement: typeof import('./src/components/announcement/Announcement.vue')['default']
    Carousel: typeof import('./src/components/carousel/Carousel.vue')['default']
    ContentBody: typeof import('./src/components/contentBody/ContentBody.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    HelpBar: typeof import('./src/components/helpBar/HelpBar.vue')['default']
    NotFoundPage: typeof import('./src/components/error/NotFoundPage.vue')['default']
    PageFooter: typeof import('./src/components/pageFooter/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/pageHeader/PageHeader.vue')['default']
    RailWayLine: typeof import('./src/components/railwayLine/RailWayLine.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFrame: typeof import('./src/components/searchFrame/SearchFrame.vue')['default']
    SearchTool: typeof import('./src/components/searchTools/SearchTool.vue')['default']
    SearchTools: typeof import('./src/components/searchTools/SearchTools.vue')['default']
    ServiceBrand: typeof import('./src/components/serviceBrand/ServiceBrand.vue')['default']
    ServiceList: typeof import('./src/components/serviceList/ServiceList.vue')['default']
  }
}

export {}
